# Generated by Django 5.0 on 2024-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.CharField(default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='auto',
            name='owners',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
