# Generated by Django 5.0 on 2024-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_mileage_auto_owners_auto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
