# Generated by Django 5.0 on 2024-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_remove_auto_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
