# Generated by Django 5.0 on 2024-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_photo_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='auto_images')),
            ],
            options={
                'verbose_name': 'фотографию',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='auto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='photo',
        ),
        migrations.AddField(
            model_name='auto',
            name='categories',
            field=models.ManyToManyField(to='auto.category'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
