# Generated by Django 5.0 on 2024-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_image_alter_auto_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='engine',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='power',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='year',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
