# Generated by Django 5.0 on 2024-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_auto_engine_auto_power_auto_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='gearbox',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
