# Generated by Django 5.0 on 2024-09-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_auto_gearbox_alter_auto_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='img1',
            field=models.ImageField(blank=True, upload_to='img1/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img2',
            field=models.ImageField(blank=True, upload_to='img2/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img3',
            field=models.ImageField(blank=True, upload_to='img3/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='img4',
            field=models.ImageField(blank=True, upload_to='img4/%Y/%m/%d/'),
        ),
    ]
