# Generated by Django 5.1.2 on 2024-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_auto_img1_auto_img2_auto_img3_auto_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='img',
            field=models.ImageField(blank=True, upload_to='auto_images'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img1',
            field=models.ImageField(blank=True, upload_to='auto_images'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img2',
            field=models.ImageField(blank=True, upload_to='auto_images'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img3',
            field=models.ImageField(blank=True, upload_to='auto_images'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img4',
            field=models.ImageField(blank=True, upload_to='auto_images'),
        ),
    ]
