version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=setting.settings
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    command: gunicorn setting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/api/media  # Подключаем папку media
      - ./staticfiles:/api/staticfiles  # Подключаем папку staticfiles

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфигурацию Nginx
      - ./media:/api/media  # Подключаем media
      - ./staticfiles:/api/staticfiles  # Подключаем staticfiles
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: